### ISSUE TITLE
报错了，没有Display_characterX和Init_Font这两个函数

### ISSUE THREAD

**Issue by gwonpy** [wangxinshuo0421/self-service-ordering-system-based-on-ARM-A53#1]
![image](https://user-images.githubusercontent.com/79096844/167828168-8b0f6091-3bf4-4b29-87d5-21775f6f281d.png)

**Comment by Z-JHAO** [comment]
> ![image](https://user-images.githubusercontent.com/79096844/167828168-8b0f6091-3bf4-4b29-87d5-21775f6f281d.png)
